'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=document.body.dataset.page;
const pages=[['overview','Overview','▦'],['projects','Projects','◩'],['tasks','My Tasks','✓'],['analytics','Analytics','↗'],['messages','Messages','✉'],['team','Team','☻'],['calendar','Calendar','▤'],['settings','Settings','⚙']];
const statuses=['To Do','In Progress','Review','Completed'];
let me,state,csrf='',taskFilter='mine',projectFilter='',calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDay=localDate(new Date()),refreshTimer;
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dateLabel(v){return v?new Date(v+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No deadline';}
function timeLabel(v){return new Date(v.replace(' ','T')+'Z').toLocaleString();}
function initials(n){return n.trim().split(/\s+/).map(v=>v[0]).slice(0,2).join('').toUpperCase();}
let pendingRequests=0,progressTimer,renderCount=0;
const busyLabels=new WeakMap();
function busy(button,on){if(!button)return;if(on){if(!busyLabels.has(button))busyLabels.set(button,button.innerHTML);button.disabled=true;button.setAttribute('aria-busy','true');button.classList.add('is-busy');}else{button.disabled=false;button.removeAttribute('aria-busy');button.classList.remove('is-busy');busyLabels.delete(button);}}
function requestProgress(start){
 pendingRequests=Math.max(0,pendingRequests+(start?1:-1));let bar=$('#request-progress');
 if(!bar){bar=document.createElement('div');bar.id='request-progress';bar.setAttribute('aria-hidden','true');document.body.append(bar);}
 clearTimeout(progressTimer);if(pendingRequests)bar.classList.add('active');else progressTimer=setTimeout(()=>bar.classList.remove('active'),160);
}
async function api(path,data){
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25000);requestProgress(true);
 try{
  const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined,signal:controller.signal});
  let body;try{body=await r.json();}catch{throw new Error('The server returned an unexpected response. Please try again.');}
  if(!r.ok){if(r.status===401&&!['login','register','forgot'].includes(page))location.replace('login.html');throw new Error(body.error||'Request failed.');}
  return body;
 }catch(e){if(e.name==='AbortError')throw new Error('This is taking longer than expected. Check your connection and try again.');if(e instanceof TypeError)throw new Error('Unable to connect. Keep the FlowSpace server running and try again.');throw e;}
 finally{clearTimeout(timeout);requestProgress(false);}
}
function toast(msg,error=false){const root=$('#toasts');if(!root)return;const el=document.createElement('div');el.className='toast';el.style.setProperty('--tc',error?'var(--bad)':'var(--ok)');const text=document.createElement('span');text.textContent=msg;const close=document.createElement('button');close.className='toast-close';close.setAttribute('aria-label','Dismiss notification');close.textContent='×';el.append(text,close);root.append(el);const dismiss=()=>{el.classList.add('out');setTimeout(()=>el.remove(),180);};close.onclick=dismiss;setTimeout(dismiss,error?6500:4000);}
function applyTheme(theme){window.FlowSpaceTheme?.apply(theme);if(!window.FlowSpaceTheme)document.documentElement.dataset.theme=theme;}
function empty(title,detail){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(detail)}</p></div>`;}
function heading(title,desc,actions=''){return `<nav class="crumb" aria-label="Breadcrumb"><a href="overview.html">FlowSpace</a> / ${esc(title)}</nav><section class="hero"><div><h1>${esc(title)}</h1><p class="muted">${esc(desc)}</p></div>${actions}</section>`;}
function button(action,label,id='',cls='primary'){return `<button class="btn ${cls}" data-action="${action}" ${id!==''?`data-id="${id}"`:''}>${label}</button>`;}
function options(list,value){return list.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('');}
function person(id){return state.team.find(p=>p.id===Number(id))?.name||'Former member';}
function projectProgress(p){const tasks=state.tasks.filter(t=>t.project_id===p.id);return tasks.length?Math.round(100*tasks.filter(t=>t.status==='Completed').length/tasks.length):0;}
function projectCards(list){return list.length?`<div class="grid">${list.map(p=>`<article class="card lift"><div class="p-top"><h3>${esc(p.title)}</h3><button class="icon-btn" data-action="favorite" data-id="${p.id}" aria-label="${p.favorite?'Unfavorite':'Favorite'} ${esc(p.title)}" aria-pressed="${!!p.favorite}">${p.favorite?'★':'☆'}</button></div><p class="p-desc">${esc(p.description)}</p><span class="badge ${p.status==='At risk'?'warn':'ok'}">${esc(p.status)}</span><div class="p-row"><span>Task completion</span><b>${projectProgress(p)}%</b></div><div class="bar" role="progressbar" aria-valuenow="${projectProgress(p)}" aria-valuemin="0" aria-valuemax="100" aria-label="${esc(p.title)} task completion"><i style="width:${projectProgress(p)}%"></i></div><div class="p-meta"><small>${dateLabel(p.due)}</small><small>${esc(p.priority)} priority</small></div><div class="project-actions">${button('edit-project','Edit',p.id,'')}${button('project-tasks','View tasks',p.id,'ghost')}${button('delete-project','Delete',p.id,'ghost danger')}</div></article>`).join('')}</div>`:empty('No projects yet','Create a project to start organizing your work.');}
function metrics(){const done=state.tasks.filter(t=>t.status==='Completed').length;const today=localDate(new Date()),end=localDate(new Date(Date.now()+7*86400000));const deadlines=[...state.tasks.filter(t=>t.status!=='Completed'),...state.projects.filter(p=>p.status!=='Completed')].filter(t=>t.due>=today&&t.due<=end).length;
 return `<section class="kpis">${[['Active projects',state.projects.filter(p=>p.status!=='Completed').length,'In this workspace'],['Completed tasks',done,`${state.tasks.length} total tasks`],['Completion rate',`${state.tasks.length?Math.round(done/state.tasks.length*100):0}%`,'Across all tasks'],['Upcoming deadlines',deadlines,'Today through the next 7 days']].map(([label,value,detail])=>`<article class="card kpi"><span class="muted">${label}</span><b>${value}</b><small class="muted">${detail}</small></article>`).join('')}</section>`;
}
function taskCard(t){const p=state.projects.find(p=>p.id===t.project_id);return `<article class="task-card" draggable="true" data-task="${t.id}" tabindex="0"><h3>${esc(t.title)}</h3><div class="task-meta"><span>${esc(p?.title||'No project')} · ${esc(t.priority)}</span><span>${esc(person(t.assignee))}</span><span>${dateLabel(t.due)}</span></div><label class="sr" for="status-${t.id}">Status for ${esc(t.title)}</label><select id="status-${t.id}" data-status="${t.id}">${options(statuses,t.status)}</select><div class="task-tools"><button data-action="edit-task" data-id="${t.id}">Edit</button><button class="danger" data-action="delete-task" data-id="${t.id}">Delete</button></div></article>`;}
function board(tasks){return `<div class="board">${statuses.map(s=>`<section class="lane" data-lane="${s}" aria-label="${s}"><h3>${s}<span class="muted">${tasks.filter(t=>t.status===s).length}</span></h3>${tasks.filter(t=>t.status===s).map(taskCard).join('')}${!tasks.some(t=>t.status===s)?'<small class="muted">No tasks</small>':''}</section>`).join('')}</div>`;}
function chart(title,values){const max=Math.max(1,...values.map(v=>v[1]));return `<article class="card"><h2>${title}</h2>${values.map(([label,count])=>`<div class="chart-row"><span>${esc(label)}</span><div class="bar"><i style="width:${count/max*100}%"></i></div><b>${count}</b></div>`).join('')}</article>`;}
let chartDays=7;
const chartColors=['#94a3b8','#0f766e','#e6ab5a','#6d5ce7'];
function trendChart(){
 const days=Array.from({length:chartDays},(_,i)=>{const d=new Date();d.setDate(d.getDate()-chartDays+1+i);return {date:localDate(d),label:d.toLocaleDateString(undefined,{month:'short',day:'numeric'}),n:state.tasks.filter(t=>t.completed_at===localDate(d)).length};});
 const max=Math.ceil(Math.max(4,...days.map(d=>d.n))/4)*4,W=640,H=240,L=42,R=18,T=22,B=34;
 const x=i=>L+i*(W-L-R)/(days.length-1),y=n=>H-B-n*(H-B-T)/max;
 const points=days.map((d,i)=>`${x(i)},${y(d.n)}`).join(' '),area=`M ${L},${H-B} L ${points.replaceAll(' ',' L ')} L ${W-R},${H-B} Z`;
 return `<article class="card trend-card"><div class="chart-title"><div><span class="eyebrow">MOMENTUM</span><h2>Completion trend</h2></div><label class="sr" for="chart-days">Chart time range</label><select id="chart-days"><option value="7" ${chartDays===7?'selected':''}>Last 7 days</option><option value="30" ${chartDays===30?'selected':''}>Last 30 days</option></select></div><p class="muted">${days.reduce((sum,d)=>sum+d.n,0)} tasks completed in this period</p><svg class="trend-svg" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="trend-title trend-desc"><title id="trend-title">Daily task completion</title><desc id="trend-desc">${days.map(d=>`${d.label}: ${d.n}`).join('; ')}</desc><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#0f766e" stop-opacity=".23"/><stop offset="100%" stop-color="#0f766e" stop-opacity=".01"/></linearGradient></defs>${Array.from({length:5},(_,i)=>{const n=max*i/4;return `<line x1="${L}" x2="${W-R}" y1="${y(n)}" y2="${y(n)}" class="chart-gridline"/><text x="${L-12}" y="${y(n)+4}" text-anchor="end" class="chart-label">${Math.round(n)}</text>`;}).join('')}<path d="${area}" fill="url(#trend-fill)"/><polyline points="${points}" fill="none" stroke="#0f766e" stroke-width="3" stroke-linejoin="round"/>${days.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d.n)}" r="${chartDays===7?5:3}" fill="#0f766e" tabindex="0"><title>${d.label}: ${d.n} completed tasks</title></circle>${i===0||i===days.length-1||i%Math.ceil(chartDays/6)===0?`<text x="${x(i)}" y="${H-8}" text-anchor="middle" class="chart-label">${d.label}</text>`:''}`).join('')}</svg>${state.tasks.length?'':'<p class="chart-empty">Complete a task to begin your trend.</p>'}<details class="chart-data"><summary>View chart data</summary><table><thead><tr><th>Date</th><th>Completed tasks</th></tr></thead><tbody>${days.map(d=>`<tr><td>${dateLabel(d.date)}</td><td>${d.n}</td></tr>`).join('')}</tbody></table></details></article>`;
}
function pieChart(){const total=state.tasks.length;let angle=-Math.PI/2;const values=statuses.map((s,i)=>({label:s,n:state.tasks.filter(t=>t.status===s).length,color:chartColors[i]}));
 const slices=values.filter(v=>v.n).map(v=>{const end=angle+v.n/total*2*Math.PI,x1=120+92*Math.cos(angle),y1=120+92*Math.sin(angle),x2=120+92*Math.cos(end),y2=120+92*Math.sin(end);const d=`M 120 120 L ${x1} ${y1} A 92 92 0 ${end-angle>Math.PI?1:0} 1 ${x2} ${y2} Z`;angle=end;return v.n===total?`<circle cx="120" cy="120" r="92" fill="${v.color}"><title>${v.label}: ${v.n} (100%)</title></circle>`:`<path d="${d}" fill="${v.color}" stroke="var(--surface)" stroke-width="3" tabindex="0"><title>${v.label}: ${v.n} (${Math.round(v.n/total*100)}%)</title></path>`;}).join('');
 return `<article class="card pie-card"><span class="eyebrow">THE BIG PICTURE</span><h2>Task status</h2><p class="muted">${total} tasks across your workspace</p><div class="pie-layout"><svg viewBox="0 0 240 240" class="pie-svg" role="img" aria-labelledby="pie-title pie-desc"><title id="pie-title">Task status pie chart</title><desc id="pie-desc">${values.map(v=>v.label+': '+v.n).join('; ')}</desc>${total?slices:'<circle cx="120" cy="120" r="92" fill="var(--surface-2)"/><text x="120" y="125" text-anchor="middle" class="chart-label">No tasks yet</text>'}</svg><ul class="chart-legend">${values.map(v=>`<li><span class="legend-dot" style="background:${v.color}"></span><span>${v.label}</span><b>${v.n}</b><small>${total?Math.round(v.n/total*100):0}%</small></li>`).join('')}</ul></div></article>`;
}
function analytics(){return `${metrics()}<section class="analytics-charts">${trendChart()}${pieChart()}</section><section class="analytics-grid">${chart('Open tasks by priority',['High','Medium','Low'].map(s=>[s,state.tasks.filter(t=>t.priority===s&&t.status!=='Completed').length]))}${chart('Tasks by teammate',state.team.map(p=>[p.name,state.tasks.filter(t=>t.assignee===p.id).length]))}</section><p class="muted analytics-note">Updated from your saved tasks · Hover over graph points and pie segments for details.</p>`;}
function calendar(){const start=new Date(calendarMonth);start.setDate(1-start.getDay());const today=localDate(new Date());let days='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const v=localDate(d);const events=state.events.filter(e=>e.date===v).sort((a,b)=>a.start.localeCompare(b.start));const due=[...state.tasks.filter(t=>t.status!=='Completed'),...state.projects.filter(p=>p.status!=='Completed')].filter(t=>t.due===v);days+=`<button class="day ${d.getMonth()!==calendarMonth.getMonth()?'other':''} ${v===today?'today':''} ${v===selectedDay?'selected':''}" data-day="${v}" aria-label="${dateLabel(v)}, ${events.length} events, ${due.length} deadlines" aria-pressed="${v===selectedDay}"><span class="day-number">${d.getDate()}</span>${events.slice(0,2).map(e=>`<span class="event-chip">${e.start} ${esc(e.title)}</span>`).join('')}${due.length?`<span class="event-chip deadline-chip">${due.length} deadline${due.length>1?'s':''}</span>`:''}${events.length>2?`<small>+${events.length-2} more</small>`:''}</button>`;}
 const events=state.events.filter(e=>e.date===selectedDay).sort((a,b)=>a.start.localeCompare(b.start));const due=[...state.tasks.filter(t=>t.status!=='Completed').map(t=>({...t,type:'Task'})),...state.projects.filter(p=>p.status!=='Completed').map(p=>({...p,type:'Project'}))].filter(t=>t.due===selectedDay);
 return `<section class="calendar-layout"><article class="card calendar-card"><div class="calendar-nav"><h2>${calendarMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button class="btn" data-action="prev-month" aria-label="Previous month">‹</button><button class="btn" data-action="today">Today</button><button class="btn" data-action="next-month" aria-label="Next month">›</button></div><div class="calendar-week">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${days}</div><p class="muted" style="margin-top:12px">Select a day to see its agenda. Times use your local timezone.</p></article><article class="card"><h2>${dateLabel(selectedDay)}</h2>${button('new-event','+ Add event','','')}${events.map(e=>`<div class="agenda-item"><small class="muted">${e.start} – ${e.end}</small><h3>${esc(e.title)}</h3><p>${esc(e.notes)}</p>${button('edit-event','Edit',e.id,'sm')}${button('delete-event','Delete',e.id,'ghost danger sm')}</div>`).join('')}${due.map(t=>`<div class="agenda-item"><span class="badge">${t.type} deadline</span><h3>${esc(t.title)}</h3>${button(t.type==='Task'?'edit-task':'edit-project','Open',t.id,'ghost sm')}</div>`).join('')}${!events.length&&!due.length?'<p class="muted" style="margin-top:18px">Nothing scheduled. Make room for what matters.</p>':''}</article></section>`;
}
function messageList(){return state.messages.length?state.messages.map(m=>`<article class="message ${m.sender===me.id?'mine':''}"><strong>${esc(person(m.sender))}</strong><p>${esc(m.body)}</p><small>${timeLabel(m.created)}</small></article>`).join(''):empty('Start the conversation','Messages are shared with members of this workspace.');}
function render(){
 const oldFocus=document.activeElement;const focusId=oldFocus?.id;const focusDay=oldFocus?.dataset?.day;const focusStatus=oldFocus?.dataset?.status;const focusAction=oldFocus?.dataset?.action;const focusActionId=oldFocus?.dataset?.id;
 const content=$('#main');const title=pages.find(p=>p[0]===page)?.[1];let html='';
 if(page==='overview'){const hour=new Date().getHours();html=heading(`Good ${hour<12?'morning':hour<18?'afternoon':'evening'}, ${me.name.split(' ')[0]}`,'Here’s what’s happening in your workspace.',button('new-project','+ Create project'))+metrics()+`<section><div class="toolbar"><h2>Active projects</h2><a class="subtle-link" href="projects.html">View all projects →</a></div>${projectCards(state.projects.filter(p=>p.status!=='Completed').slice(0,4))}</section><section><div class="toolbar"><h2>Your next tasks</h2><a class="subtle-link" href="tasks.html">Open task board →</a></div>${state.tasks.some(t=>t.assignee===me.id&&t.status!=='Completed')?`<div class="grid">${state.tasks.filter(t=>t.assignee===me.id&&t.status!=='Completed').slice(0,3).map(taskCard).join('')}</div>`:empty('You’re all caught up','Add a task or ask your team to assign one.')}</section>`;}
 if(page==='projects')html=heading(title,'Plan the work. Track the progress.',button('new-project','+ New project'))+`<section><div class="toolbar"><h2>${state.projects.length} projects</h2><label class="sr" for="project-filter">Filter projects</label><select id="project-filter">${options(['All projects','Favorites','On track','At risk','In review','Completed'],projectFilter||'All projects')}</select></div>${projectCards(state.projects.filter(p=>!projectFilter||projectFilter==='All projects'||(projectFilter==='Favorites'?p.favorite:p.status===projectFilter)))}</section>`;
 if(page==='tasks'){const projectId=new URLSearchParams(location.search).get('project');const tasks=state.tasks.filter(t=>(taskFilter==='all'||t.assignee===me.id)&&(!projectId||t.project_id===Number(projectId)));html=heading(title,'Drag tasks between columns, or use the status dropdown.',button('new-task','+ New task'))+`<section><div class="toolbar"><h2>${projectId?esc(state.projects.find(p=>p.id===Number(projectId))?.title||'Project'): 'Task board'}</h2><label class="sr" for="task-filter">Task scope</label><select id="task-filter"><option value="mine" ${taskFilter==='mine'?'selected':''}>Assigned to me</option><option value="all" ${taskFilter==='all'?'selected':''}>All workspace tasks</option></select>${projectId?'<a href="tasks.html" class="subtle-link">Clear project filter</a>':''}</div>${board(tasks)}</section>`;}
 if(page==='analytics')html=heading(title,'A clear view of how your work is moving.',button('export','Export CSV','',''))+analytics();
 if(page==='calendar')html=heading(title,'Your schedule and deadlines, together.',button('new-event','+ New event'))+calendar();
 if(page==='messages')html=heading(title,'A shared conversation for your workspace.')+`<section class="card messages-box"><div class="toolbar"><h2>${esc(state.workspace.name)} chat</h2><small class="muted">Updates every 5 seconds</small></div><div id="message-history" class="message-history" aria-label="Messages">${messageList()}</div><form id="message-form" class="message-compose"><label>Message<textarea name="body" required maxlength="2000" rows="2" placeholder="Write to your team…"></textarea></label><button class="btn primary">Send</button></form><p class="error" id="message-error" role="alert"></p></section>`;
 if(page==='team')html=heading(title,'The people who make this workspace happen.',me.id===state.workspace.owner?button('invite','+ Invite member'):'')+`<section class="grid">${state.team.map(p=>`<article class="card member-card"><span class="avatar" style="--c:var(--accent)">${initials(p.name)}</span><div><h3>${esc(p.name)} ${p.id===me.id?'(you)':''}</h3><p class="muted">${esc(p.email)}</p><small>${p.id===state.workspace.owner?'Workspace owner':'Member'}</small></div>${me.id===state.workspace.owner&&p.id!==me.id?button('remove-member','Remove',p.id,'ghost danger sm'):''}</article>`).join('')}</section><section class="card"><h2>Pending invitations</h2><p class="muted">No email is sent. Share the app address with your teammate; they must register using the invited email on this same server. See README for access from another computer.</p><div class="invite-list">${state.invitations.map(i=>`<div class="invite-row"><span>${esc(i.email)}</span>${me.id===state.workspace.owner?button('revoke-invite','Revoke',i.id,'ghost danger sm'):''}</div>`).join('')||'<p class="muted">No pending invitations.</p>'}</div></section>`;
 if(page==='settings')html=heading(title,'Make this space work for you.')+`<section class="settings-grid"><article class="card"><h2>Profile & preferences</h2><form id="settings-form"><label>Your name<input name="name" value="${esc(me.name)}" required maxlength="80" autocomplete="name"></label><label>Email<input value="${esc(me.email)}" disabled></label><label>Mobile number<input name="mobile" type="tel" required maxlength="22" autocomplete="tel" value="${esc(me.mobile||'')}" placeholder="+91 98765 43210"><small class="field-hint">Include your country code. Email is used for OTP.</small></label><label>Workspace name<input name="workspace" value="${esc(state.workspace.name)}" required maxlength="80" ${me.id!==state.workspace.owner?'readonly':''}></label><label>Theme<select name="theme">${options(['light','dark'],me.theme)}</select></label><p class="error" id="settings-error" role="alert"></p><button class="btn primary">Save changes</button></form></article><article class="card"><h2>Change password</h2><form id="password-form"><label>Current password<input name="current_password" type="password" required autocomplete="current-password"></label><label>New password<input name="new_password" type="password" required minlength="8" maxlength="256" autocomplete="new-password"></label><p class="error" id="password-error" role="alert"></p><button class="btn">Update password</button></form><hr style="margin:24px 0;border:0;border-top:1px solid var(--line)"><h2>Session</h2><p class="muted">Signed in as ${esc(me.email)}</p>${button('logout','Log out','','ghost danger')}</article></section>`;
 content.innerHTML=html;content.classList.toggle('first-render',renderCount++===0);if(page==='settings')appendSecuritySettings().catch(e=>toast(e.message,true));content.setAttribute('aria-busy','false');
 $('.content').classList.toggle('wide',['calendar','messages','analytics','settings','tasks'].includes(page));
 $('#timeline').innerHTML=state.activity.slice(-8).reverse().map(a=>`<li><p>${esc(a.body)}</p><small>${timeLabel(a.created)}</small></li>`).join('')||'<li class="muted">Your workspace activity will appear here.</li>';
 $('#workspace-label').textContent=state.workspace.name;$('#profile').textContent=initials(me.name);bind();
 if(page==='messages')$('#message-history').scrollTop=$('#message-history').scrollHeight;
 const restore=focusId?document.getElementById(focusId):focusDay?$(`[data-day="${focusDay}"]`):focusStatus?$(`[data-status="${focusStatus}"]`):focusAction?$(`[data-action="${focusAction}"]${focusActionId?'[data-id="'+focusActionId+'"]':''}`):null;restore?.focus({preventScroll:true});
}
function bind(){
 $('#chart-days')?.addEventListener('change',e=>{chartDays=Number(e.target.value);render();});
 $('#project-filter')?.addEventListener('change',e=>{projectFilter=e.target.value;render();});
 $('#task-filter')?.addEventListener('change',e=>{taskFilter=e.target.value;render();});
 $$('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;render();});
 $$('[data-status]').forEach(s=>s.onchange=()=>moveTask(Number(s.dataset.status),s.value));
 $$('[draggable]').forEach(t=>t.ondragstart=e=>e.dataTransfer.setData('text/plain',t.dataset.task));
 $$('[data-lane]').forEach(l=>{l.ondragover=e=>{e.preventDefault();l.classList.add('dragover');};l.ondragleave=()=>l.classList.remove('dragover');l.ondrop=e=>{e.preventDefault();l.classList.remove('dragover');const id=Number(e.dataTransfer.getData('text/plain'));if(state.tasks.some(t=>t.id===id))moveTask(id,l.dataset.lane);};});
 $('#message-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,b=form.querySelector('button');busy(b,true);try{await api('message',Object.fromEntries(new FormData(form)));form.reset();state=await api('data');$('#message-history').innerHTML=messageList();$('#message-history').scrollTop=$('#message-history').scrollHeight;$('#message-error').textContent='';}catch(err){$('#message-error').textContent=err.message;}finally{busy(b,false);}});
 $('#settings-form')?.addEventListener('submit',e=>saveSettings(e,false));$('#password-form')?.addEventListener('submit',e=>saveSettings(e,true));
}
async function saveSettings(e,password){e.preventDefault();const b=e.target.querySelector('button');busy(b,true);try{const values=Object.fromEntries(new FormData(e.target));await api('settings',password?{...values,name:me.name,theme:me.theme,workspace:state.workspace.name}:values);me=(await api('me')).user;applyTheme(me.theme);await reload();toast(password?'Password updated.':'Settings saved.');}catch(err){$(password?'#password-error':'#settings-error').textContent=err.message;}finally{busy(b,false);}}
async function reload(){const content=$('#main');content?.setAttribute('aria-busy','true');try{state=await api('data');render();}finally{content?.setAttribute('aria-busy','false');}}
async function moveTask(id,status){const t=state.tasks.find(t=>t.id===id);try{await api('task/save',{...t,status});await reload();toast('Task status updated.');}catch(e){toast(e.message,true);await reload();}}
function field(label,name,value='',type='text',required=false,extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${extra}></label>`;}
function select(label,name,list,value){return `<label>${label}<select name="${name}">${options(list,value)}</select></label>`;}
function editor(kind,id){
 const existing=id?state[kind==='project'?'projects':kind==='task'?'tasks':'events'].find(r=>r.id===Number(id)):null;
 let fields='';
 if(kind==='project'){const p=existing||{priority:'Medium',status:'On track'};fields=field('Project name','title',p.title,'text',true,'maxlength="120"')+`<label>Description<textarea name="description" maxlength="1000" rows="3">${esc(p.description)}</textarea></label>`+field('Deadline','due',p.due,'date')+`<div class="row2">${select('Priority','priority',['Low','Medium','High'],p.priority)}${select('Status','status',['On track','At risk','In review','Completed'],p.status)}</div>`;}
 if(kind==='task'){const t=existing||{priority:'Medium',status:'To Do',assignee:me.id,project_id:new URLSearchParams(location.search).get('project')};fields=field('Task name','title',t.title,'text',true,'maxlength="160"')+`<div class="row2">${select('Status','status',statuses,t.status)}${select('Priority','priority',['Low','Medium','High'],t.priority)}</div>`+field('Deadline','due',t.due,'date')+`<label>Project<select name="project_id"><option value="">No project</option>${state.projects.map(p=>`<option value="${p.id}" ${Number(t.project_id)===p.id?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label><label>Assigned to<select name="assignee">${state.team.map(p=>`<option value="${p.id}" ${p.id===t.assignee?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>`;}
 if(kind==='event'){const v=existing||{date:selectedDay,start:'09:00',end:'10:00'};fields=field('Event title','title',v.title,'text',true,'maxlength="120"')+field('Date','date',v.date,'date',true)+`<div class="row2">${field('Start time','start',v.start,'time',true)}${field('End time','end',v.end,'time',true)}</div><label>Notes<textarea name="notes" rows="3" maxlength="1000">${esc(v.notes)}</textarea></label>`;}
 if(kind==='invite')fields=field('Teammate email','email','','email',true)+`<p class="muted">They can join by registering with this email. No email will be sent automatically.</p>`;
 const dialog=$('#editor');dialog.innerHTML=`<h2 id="dialog-title">${kind==='invite'?'Invite teammate':`${id?'Edit':'New'} ${kind}`}</h2><form id="editor-form">${fields}<p class="error" id="editor-error" role="alert"></p><div class="actions"><button type="button" class="btn ghost" data-action="close">Cancel</button><button class="btn primary">${kind==='invite'?'Create invitation':'Save '+kind}</button></div></form>`;dialog.showModal();dialog.classList.remove('closing');
 $('#editor-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type="submit"]')||e.target.querySelector('.primary');busy(b,true);try{const values=Object.fromEntries(new FormData(e.target));if(id)values.id=Number(id);if(kind==='task'){values.project_id=values.project_id?Number(values.project_id):null;values.assignee=Number(values.assignee);}await api(kind==='invite'?'invite':kind+'/save',values);closeEditor();await reload();toast(kind==='invite'?'Invitation created.':'Changes saved.');}catch(err){$('#editor-error').textContent=err.message;}finally{busy(b,false);}};
}
function confirmAction(title,description,callback){const d=$('#editor');d.innerHTML=`<h2 id="dialog-title">${esc(title)}</h2><p>${esc(description)}</p><p class="error" id="editor-error" role="alert"></p><div class="actions" style="margin-top:24px"><button class="btn ghost" data-action="close">Cancel</button><button class="btn danger" id="confirm-delete">Confirm</button></div>`;d.showModal();d.classList.remove('closing');$('#confirm-delete').onclick=async e=>{e.target.disabled=true;try{await callback();closeEditor();await reload();toast('Done.');}catch(err){$('#editor-error').textContent=err.message;e.target.disabled=false;}};}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=Number(b.dataset.id);if(action==='toggle-theme'){await toggleTheme(b);return;}try{
 if(action==='logout'){await api('logout',{});clearInterval(refreshTimer);location.replace('login.html');}
 if(action==='close')closeEditor();
 if(action==='new-project'||action==='edit-project')editor('project',id);
 if(action==='new-task'||action==='edit-task')editor('task',id);
 if(action==='new-event'||action==='edit-event')editor('event',id);
 if(action==='invite')editor('invite');
 if(action==='favorite'){await api('project/favorite',{id});await reload();}
 if(action==='project-tasks')location.href='tasks.html?project='+id;
 if(action.startsWith('delete-')){const kind=action.slice(7);confirmAction('Delete '+kind+'?',kind==='project'?'Linked tasks will remain and become unassigned to a project.':'This will permanently delete this '+kind+'.',()=>api(kind+'/delete',{id}));}
 if(action==='revoke-invite')confirmAction('Revoke invitation?','This email will no longer be able to join your workspace.',()=>api('invite/delete',{id}));
 if(action==='remove-member')confirmAction('Remove member?','Their assigned tasks will be reassigned to you. They will receive an empty personal workspace.',()=>api('member/remove',{id}));
 if(action==='prev-month'||action==='next-month'){calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+(action==='next-month'?1:-1),1);render();}
 if(action==='today'){calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);selectedDay=localDate(new Date());render();}
 if(action==='export'){const rows=[['Task','Project','Status','Priority','Assignee','Due'],...state.tasks.map(t=>[t.title,state.projects.find(p=>p.id===t.project_id)?.title||'',t.status,t.priority,person(t.assignee),t.due])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='flowspace-tasks.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 }catch(err){toast(err.message,true);}
});
async function boot(){
 if(['login','register','forgot'].includes(page)){await authBoot();return;}
 try{const result=await api('me');me=result.user;csrf=result.csrf;applyTheme(me.theme);
 $('#nav').innerHTML=pages.map(([slug,title,icon])=>`<li><a href="${slug}.html" ${slug===page?'aria-current="page"':''}><span class="ic">${icon}</span><span class="lbl">${title}</span></a></li>`).join('');
 if(page==='tasks'&&new URLSearchParams(location.search).has('project'))taskFilter='all';
 $('#menu').onclick=()=>{$('#app').classList.toggle('open');$('#menu').setAttribute('aria-expanded',$('#app').classList.contains('open'));};$('#scrim').onclick=()=>{$('#app').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');};
 $('#q').oninput=e=>{const q=e.target.value.trim().toLowerCase();const results=$('#results');results.hidden=!q;if(!q)return;const list=[...state.projects.map(p=>({label:p.title,url:'tasks.html?project='+p.id,type:'Project'})),...state.tasks.map(t=>({label:t.title,url:'tasks.html'+(t.project_id?'?project='+t.project_id:''),type:'Task'}))].filter(r=>r.label.toLowerCase().includes(q));results.innerHTML=list.slice(0,8).map(r=>`<a href="${r.url}"><small>${r.type}</small> ${esc(r.label)}</a>`).join('')||'<p class="muted">No matches.</p>';};
 document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#results').hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#results').hidden=true;});
 await reload();$('#app').hidden=false;$('#boot-loader')?.remove();
 if(page==='messages')refreshTimer=setInterval(async()=>{if(document.hidden)return;try{const next=await api('data');const changed=next.messages.length!==state.messages.length;state=next;if(changed){const h=$('#message-history'),bottom=h.scrollHeight-h.scrollTop-h.clientHeight<60;h.innerHTML=messageList();if(bottom)h.scrollTop=h.scrollHeight;}}catch{}},5000);
 }catch(e){if(e.message!=='Please log in.'){document.body.innerHTML='<main class="auth"><section class="card"><h1>Unable to load workspace</h1><p>'+esc(e.message)+'</p><p>Make sure you started the Python server, then reload this page.</p><a href="overview.html">Try again</a></section></main>';}}
}
let authConfiguration,otpTimer;
function questionFields(questions){return [0,1].map(i=>`<label>Security question ${i+1}<select name="question${i}" required>${questions.map((q,n)=>`<option value="${n}" ${n===i?'selected':''}>${esc(q)}</option>`).join('')}</select></label><label>Your answer<input name="answer${i}" required minlength="3" maxlength="100" autocomplete="off" placeholder="An answer you will remember"></label>`).join('');}
function authValues(form){const v=Object.fromEntries(new FormData(form));if('question0' in v){v.questions=[Number(v.question0),Number(v.question1)];v.answers=[v.answer0,v.answer1];delete v.question0;delete v.question1;delete v.answer0;delete v.answer1;}if(page==='register')v.theme=document.documentElement.dataset.theme||'light';return v;}
function showOTP(result){
 clearInterval(otpTimer);const container=$('#auth-content');const started=Date.now();let challenge=result.challenge;
 $('#auth-description').textContent=page==='register'?'One last step before your workspace is ready.':page==='forgot'?'Confirm your email before recovering your account.':'It’s time for a quick account verification.';
 container.innerHTML=`<div class="verification-header"><span class="verification-icon">✉</span><h3>Check your inbox</h3><p class="muted">Enter the six-digit code for <strong>${esc(result.email)}</strong>.</p></div>${result.demo_code?`<div class="demo-code"><strong>Local demo — no email was sent</strong><p>Use this test code: <b>${result.demo_code}</b></p><small>This does not verify ownership of a real email address.</small></div>`:''}<form id="otp-form"><label for="otp-code">Verification code</label><input id="otp-code" name="code" class="otp-input" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" minlength="6" required placeholder="000000"><div class="otp-meta"><span id="otp-expiry">Expires in 10:00</span><button type="button" class="link" id="otp-resend" disabled>Resend in 60s</button></div><p class="error" id="auth-error" role="alert"></p><button class="btn primary auth-submit">Verify & continue <span>→</span></button></form><a class="back-link" href="${page}.html">← Use a different email</a>`;
 $('#otp-code').focus();
 const tick=()=>{const elapsed=Math.floor((Date.now()-started)/1000),left=Math.max(0,600-elapsed),resend=Math.max(0,60-elapsed);$('#otp-expiry').textContent=`${left?'Expires in':'Code expired'} ${left?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`:''}`;$('#otp-resend').disabled=!!resend;$('#otp-resend').textContent=resend?`Resend in ${resend}s`:'Resend code';if(!left){$('#otp-form .primary').disabled=true;clearInterval(otpTimer);}};tick();otpTimer=setInterval(tick,1000);
 $('#otp-resend').onclick=async()=>{const b=$('#otp-resend');busy(b,true);try{showOTP(await api('auth/resend',{challenge}));}catch(e){$('#auth-error').textContent=e.message;busy(b,false);}};
 $('#otp-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');busy(b,true);try{const response=await api('auth/verify',{challenge,code:$('#otp-code').value});clearInterval(otpTimer);if(response.step==='reset')showRecovery(response);else location.replace('overview.html');}catch(err){$('#auth-error').textContent=err.message;busy(b,false);}};
}
function showRecovery(result){
 $('#auth-description').textContent='Email confirmed. Complete your account recovery.';
 $('#auth-content').innerHTML=`<div class="verified-banner">✓ Email code confirmed</div><form id="reset-form">${result.questions.map((q,i)=>`<label>${esc(q)}<input name="answer${i}" required maxlength="100" autocomplete="off" placeholder="Your security answer"></label>`).join('')}${result.legacy?'<p class="muted">This account predates security questions. Your verified email code authorizes recovery. Add questions in Settings after logging in.</p>':''}<label>New password<input name="password" type="password" required minlength="8" maxlength="256" autocomplete="new-password" placeholder="At least 8 characters"></label><label>Confirm new password<input name="confirm" type="password" required minlength="8" maxlength="256" autocomplete="new-password"></label><p class="error" id="auth-error" role="alert"></p><button class="btn primary auth-submit">Reset password <span>→</span></button></form>`;
 $('#reset-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');const v=Object.fromEntries(new FormData(e.target));if(v.password!==v.confirm){$('#auth-error').textContent='The passwords do not match.';return;}busy(b,true);try{await api('recovery/reset',{challenge:result.challenge,password:v.password,answers:result.questions.map((q,i)=>v['answer'+i])});$('#auth-content').innerHTML='<div class="verification-header"><span class="verification-icon">✓</span><h3>Password updated</h3><p class="muted">You’re ready for a fresh start. All previous sessions have been signed out.</p></div><a class="btn primary auth-submit" href="login.html">Back to login →</a>';}catch(err){$('#auth-error').textContent=err.message;busy(b,false);}};
}
async function authBoot(){
 const submit=$('#auth-form .primary');busy(submit,true);
 try{await api('me');if(page!=='forgot'){location.replace('overview.html');return;}}catch{}
 try{authConfiguration=await api('auth/config');const n=$('#mail-notice');if(authConfiguration.demo){n.hidden=false;n.innerHTML='<strong>UI/UX demo mode</strong><br>Test codes appear on screen. No real email is sent.';}else if(!authConfiguration.mail_ready){n.hidden=false;n.innerHTML='<strong>Email setup needed</strong><br>Configure email delivery using EMAIL_SETUP.md to enable verification.';}if(page==='register')$('#signup-questions').innerHTML=questionFields(authConfiguration.questions);busy(submit,false);
 $('#auth-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');busy(b,true);$('#auth-error').textContent='';try{const response=await api(page==='forgot'?'recovery/start':page,authValues(e.target));if(response.step==='otp')showOTP(response);else location.replace('overview.html');}catch(err){$('#auth-error').textContent=err.message;busy(b,false);}};
 }catch(e){$('#auth-error').textContent='Could not connect. Start the Python server and reload.';busy(submit,false);}
}
async function appendSecuritySettings(){
 const config=await api('auth/config');const grid=$('.settings-grid');if(!grid)return;
 const card=document.createElement('article');card.className='card security-settings';card.innerHTML=`<span class="eyebrow">ACCOUNT PROTECTION</span><h2>Recovery questions</h2><p class="muted">${me.security_configured?'Replace your questions and answers below.':'Set up recovery questions for your account.'} Email verification is also required for password recovery.</p><form id="security-form">${questionFields(config.questions)}<label>Confirm current password<input name="current_password" type="password" required autocomplete="current-password"></label><p class="error" id="security-error" role="alert"></p><button class="btn primary">Save recovery questions</button></form>`;grid.append(card);
 $('#security-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');busy(b,true);try{await api('security/questions',authValues(e.target));me.security_configured=true;e.target.reset();toast('Recovery questions saved.');}catch(err){$('#security-error').textContent=err.message;}finally{busy(b,false);}};
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-password]');if(b){const input=document.getElementById(b.dataset.password);input.type=input.type==='password'?'text':'password';b.textContent=input.type==='password'?'Show':'Hide';b.setAttribute('aria-label',input.type==='password'?'Show password':'Hide password');}});

async function toggleTheme(button){
 const old=document.documentElement.dataset.theme||'light',next=old==='dark'?'light':'dark';applyTheme(next);busy(button,true);
 try{if(me){await api('theme',{theme:next});me.theme=next;const select=$('#settings-form [name="theme"]');if(select)select.value=next;} }
 catch(e){applyTheme(old);toast(e.message,true);}finally{busy(button,false);}
}
let editorReturnFocus;
function closeEditor(){const dialog=$('#editor');if(!dialog?.open)return;dialog.classList.add('closing');setTimeout(()=>{dialog.close();dialog.classList.remove('closing');editorReturnFocus?.focus?.({preventScroll:true});},window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:130);}
function setupInteractions(){
 const dialog=$('#editor');if(dialog){dialog.addEventListener('cancel',e=>{e.preventDefault();closeEditor();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeEditor();}});}
 document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action&&(/^(new-|edit-)/.test(action)||action==='invite'))editorReturnFocus=document.activeElement;},true);
 document.addEventListener('input',e=>{if(e.target.matches('input,textarea,select')){e.target.removeAttribute('aria-invalid');const error=e.target.closest('form')?.querySelector('.error');if(error)error.textContent='';}});
 document.addEventListener('invalid',e=>{e.target.setAttribute('aria-invalid','true');},true);
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'&&$('#q')){e.preventDefault();$('#q').focus();}if(e.key==='Escape'){$('#app')?.classList.remove('open');$('#menu')?.setAttribute('aria-expanded','false');}});
}
setupInteractions();boot();
